### ISSUE TITLE
in `customize_button'; undefined method `capture' for 0:Fixnum

### ISSUE THREAD

**Issue by Lapizistik** [decko-commons/decko#326]
On a fresh install I want to customize the skin and get errors on the skin overview. Right of the apply button I get the following error message for each skin (shown below for _cerulean_):
> Error rendering: _cerulean_ skin (customize_button view)

Steps to reproduce: 
Create a new decko instance (new, seed), start the server, create a user, navigate to page ***all**, open the **style** rule.
The logfile says:
> undefined method `capture' for 0:Fixnum
>
> ["/var/lib/gems/2.3.0/gems/card-1.96.8/mod/machines/set/abstract/skin_box.rb:17:in `customize_button'", "/var/lib/gems/2.3.0/gems/card-1.96.8/mod/machines/set/abstract/skin_box.rb:12:in `block (2 levels) in <module:SkinBox>'", …

21 times (as there are 21 skins).

ruby 2.3.3p222, decko 0.6.8, card 1.96.8

[Gemfile.lock.txt](https://github.com/decko-commons/decko/files/2906220/Gemfile.lock.txt)

(I had errors before trying to upgrade a decko 0.4.x install to 0.6 (this is why I did a fresh install), but I am not sure whether these are related to this).

**Comment by ethn** [comment]
Thanks for letting us know.  We're about to put out 0.7 and want to make sure it has a fix for this.

Can I just confirm that after the new install, you seeded with fresh data?

**Comment by ethn** [comment]
Nevermind, we figured out the problem. It has to do with the ruby version and a change in how they handle regex matching for ruby symbols.  We'll have a fix in 0.7 so this works with 2.3 (which you're using), but if you need to get things working right away, any ruby newer than 2.4.1 should work.

**Comment by ethn** [comment]
Correction: it looks like we're upping the minimum required ruby version to 2.4.1 in Decko 0.7 for multiple reasons.  So a ruby upgrade will be needed one way or another.

**Comment by Lapizistik** [comment]
Thanks for your work!
